### PR TITLE
Bring CUDA support to GNSSSignals.jl

### PR DESCRIPTION
**Pull request by ozmaden**
This brings GPU functionality (at the moment only CUDA) to `GNSSSignals.jl`

- ~~Conditional GPU usage has been implemented via the `use_gpu[]` flag set at precompilation~~ (edit: see discussion below)
- ~~Based on available hardware GNSS codes are loaded into either RAM or GPU memory~~
- Conditional GPU usage has been implemented via passing of the `use_gpu` argument
- `AbstractGNSS` types have been tweaked accordingly, functions are dispatched on the array type of the codes
- Test functions expanded to test both CPU and GPU functionality

New GPU functionality will come in hand once the GPU based tracking loop in `Tracking.jl` is merged.

### CODE REVIEW

**Comment by zsoerenm** [comment]
I wonder if the code should be on the GPU by default, if a graphic card is present.
If it would be faster for all cases, I would agree, but this is not the case, is it?
Shouldn't we make it an opt in, instead of an opt out?
What's your opinion @dominformant ?

**Comment by ozmaden** [comment]
@zsoerenm I think you bring up a very good point. 

To get a better perspective, we would need to implement a way to track both CPU and GPU branch performances by using something like [PkgBenchmark.jl](https://github.com/JuliaCI/PkgBenchmark.jl) and running CI to generate auto-reports on a service that allows for CUDA support. These are, to my limited knowledge, exclusively paid platforms. Nevertheless, even then it is pretty much _never_ trivially guaranteed that the GPU functions would outperform the CPU. Consider simple cases like an EPL correlator with one antenna.

We can surely take the route of the safest approach and let user _opt in_ upon loading the package to set `GNSSSignals.use_gpu[] = true` themselves. I think it is a good idea.

In the future it might be smart to write a sort of `tune` function, which takes a look at the system specs, runs a few benchmarks and decides what's best.

**Comment by zsoerenm** [comment]
A paid service is unfortunately out of reach. However, for testing purposes we can use buildkite: https://github.com/JuliaGPU/buildkite
> We can surely take the route of the safest approach and let user opt in upon loading the package to set GNSSSignals.use_gpu[] = true themselves.

I favor a different approach. Instead of a global variable we can use a local variable that is passed to the constructor of AbstractGNSS (e.g. `GPSL1(use_gpu = true)`)
What do you think?

**Comment by ozmaden** [comment]
>  However, for testing purposes we can use buildkite: https://github.com/JuliaGPU/buildkite

Looks promising, didn't know about it, thanks!

> Instead of a global variable we can use a local variable that is passed to the constructor of AbstractGNSS (e.g. `GPSL1(use_gpu = true)`)

For a while I had this implemented, and we can certainly take that approach. 
Only thing I was afraid of is forgetting to include that optional argument each time :smile: 
Other than that, fine by me :+1:

**Comment by zsoerenm** [comment]
> Only thing I was afraid of is forgetting to include that optional argument each time

In theory `GPSL1` should only be called once and saved in variable. Although possible, it does not make sense to have multiple `AbstractGNSS` of the same type as they are immutable.

**Comment by ozmaden** [comment]
> > Only thing I was afraid of is forgetting to include that optional argument each time
> 
> In theory `GPSL1` should only be called once and saved in variable. Although possible, it does not make sense to have multiple `AbstractGNSS` of the same type as they are immutable.

You are right, I am on it.

**Comment by zsoerenm** [comment]
Another note: For type stability it might be better to use `GPSL1(use_gpu = Val(true))` instead of `GPSL1(use_gpu = true)`. With this you can dispatch on the argument and return a type stable `AbstractGNSS`.

**Comment by ozmaden** [comment]
> For type stability it might be better to use `GPSL1(use_gpu = Val(true))`

I've implemented it the way you described it, take a look. Let me know if something's wrong.

**Comment by zsoerenm** [comment]
I think you've forgotten to add the argument `use_gpu = Val(true)` inside the cude tests ;)
I have added that in the last commit. I have also reduced the code duplication.
Could you test this on the GPU again?

**Comment by ozmaden** [comment]
> I think you've forgotten to add the argument `use_gpu = Val(true)` inside the cuda tests ;)
Yep, my bad :smile: 
> Could you test this on the GPU again?
Doing it now, seems some tests are still broken. Going too look into that and fix it.

**Comment by ozmaden** [comment]
CUDA tests are now successful :+1:

**Pull request merged**
